# Generated by Django 5.1.7 on 2025-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='translation',
            name='audio',
            field=models.CharField(max_length=255),
        ),
    ]
